### ISSUE TITLE
Spring @Async annotation instead of DistributiveEventMulticaster

### ISSUE THREAD

**Issue by borjapazr** [3BRS/spring-events#2]
To make asynchronous listeners why don't you annotate the methods `onApplicationEvent` of the `ApplicationListener` classes with the `@Async` annotation instead of creating the `DistributiveEventMulticaster`? Is there a difference?

**Comment by jabunovoty** [comment]
Because I wrote it 5 years ago and I have no clue about `@Async` at that time ;-) 
It is definitely a good idea. You can try to create a PR but I am no longer part of this org
and I do not maintain this project any more... Spring 4, Java 7, ...
